### ISSUE TITLE
Controls are switched on Oculus 2

### ISSUE THREAD

**Issue by Pixelartist** [menchelab/VRNetzer#2]
Hello,

I was just using your basic demo to check how this amazing project is working. I was able to somewhat get around, but for me the controls are switch (left hadn is right, right left). I am currently using an Oculus Quest 2, would be great if you could help out if there is any kind of profile for the different VR sets which I could help out with.

**Comment by larsjuhljensen** [comment]
I am observing the exact same problem with Quest 2.

**Comment by sepppirch** [comment]
VRNetzer was developed on vive (which has symetrical controllers) we will implement configurations for other headsets in the future. for now, there is a variable in
\VR_Module\Content\data\config.txt 
called 'lefthanded' that you can set to true to switch the UI to the other hand.
hope this helps!
